language: node_js
node_js:
  - 12
  

  

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/fruitbask_test

node_js:  
  - 14

before_script:
  - psql -c 'create database  fruitbask_test' -U postgres
  - psql -U postgres -d fruitbask_test -a -f basket.sql

services:
  - postgresql
  